;; This logfile was generated automatically by `xindy'
;; at 03.06.2017  18:08:38
;; Indexstyle: "/tmp/obH7lyAjKU", Rawindex: "/tmp/IcTvptoLF6", Output: "20170529_thesis_appendix_chapt3.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "€¼Ãå€" -> "A"
Letter-group: "Ú†€" -> "T"
Letter-group: "††´—" -> "C"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "€¼Ãå€" -> "A"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "††´—" -> "C"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ú†€" -> "T"